# MARK: - Edit this file if you want to change the organization

EXTENSION_MAPPING = {
    "Ducuments": [
        ".pdf",
        ".doc",
        ".docx",
        ".txt",
        ".odt",
        ".xls",
        ".xlsx",
        ".ppt",
        ".pptx",
        ".csv",
    ],
    "Images": [
        ".jpg",
        ".jpeg",
        ".png",
        ".gif",
        ".bmp",
        ".svg",
        ".ico",
        ".tiff",
        ".webp",
        ".heic",
    ],
    "Videos": [
        ".mp4",
        ".avi",
        ".mkv",
        ".mov",
        ".wmv",
        ".flv",
        ".webm",
        ".m4v",
        ".mpg",
        ".mpeg",
    ],
    "Audio": [".mp3", ".wav", ".flac", ".aac", ".ogg", ".wma", ".m4a", ".opus"],
    "Zipped Files": [".zip", ".rar", ".7z", ".tar", ".gz", ".bz2", ".xz", ".dmg"],
    "Code": [
        ".py",
        ".js",
        ".html",
        ".css",
        ".cpp",
        ".java",
        ".c",
        ".go",
        ".rs",
        ".swift",
        ".json",
        ".xml",
        ".yaml",
        ".yml",
    ],
    "Apps": [".app", ".pkg", ".dmg"],
    "Data": [".sql", ".db", ".sqlite"],
    "Design": [".psd", ".ai", ".sketch", ".fig", ".xd"],
    "Fonts": [".ttf", ".otf", ".woff", ".woff2"],
    "Ebooks": [".epub", ".mobi", ".azw", ".azw3"],
}
